runtime: nodejs16

handlers:
- url: /
  static_files: dist/frontend/index.html
  upload: dist/frontend/index.html

- url: /search/.*
  static_files: dist/frontend/index.html
  upload: dist/frontend/index.html

- url: /watchlist
  static_files: dist/frontend/index.html
  upload: dist/frontend/index.html

- url: /portfolio
  static_files: dist/frontend/index.html
  upload: dist/frontend/index.html

- url: /
  static_dir: dist/frontend
